apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: cocktail-virt
  labels:
    app: cocktail-virt
    cocktail-virt.io/version: { { .Values.tag } }
    cocktail-virt.io/managed: "true"
data:
  basicauth.conf: |
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/secret.d/.htpasswd;
