apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-virt-manager
  namespace: hpc-virt-manager
  labels:
    app: hpc-virt-manager
    hpc-virt-manager.io/version: 1.0.0
spec:
  selector:
    matchLabels:
      app: hpc-virt-manager
      hpc-virt-manager.io/version: 1.0.0
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hpc-virt-manager
        hpc-virt-manager.io/version: 1.0.0
    spec:
      containers:
        - name: hpcvirtmanager
          image: puru2024/namutech:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsGroup: 30000
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/nginx
            - name: run-volume
              mountPath: /var/run
            - name: auth-config
              mountPath: /etc/nginx/auth.d/
            - name: auth-secret
              mountPath: /etc/nginx/secret.d/
            - name: prometheus-config
              mountPath: /etc/nginx/location.d/
      serviceAccountName: hpc-virt-manager
      restartPolicy: Always
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
        - name: auth-config
          configMap:
            name: auth-config
            optional: true
        - name: auth-secret
          secret:
            secretName: auth-secret
            optional: true
        - name: prometheus-config
          configMap:
            name: prometheus-config
            optional: true
