apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
description: Priority class for VMs which should not be preemtited.
metadata:
  name: vm-standard
  labels:
    app: cocktail-virt
    cocktail-virt.io/version: 1.0.0
    cocktail-virt.io/managed: "true"
preemptionPolicy: Never
value: 999999999

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
description: Priority class for VMs which are allowed to be preemtited.
metadata:
  name: vm-preemptible
  labels:
    app: cocktail-virt
    cocktail-virt.io/version: 1.0.0
    cocktail-virt.io/managed: "true"
preemptionPolicy: PreemptLowerPriority
value: 1000000
