name: Docker Image CI

on:
  push:
    branches:
      - "dev"
      - "main"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{steps.package-version.outputs.current-version}}

      - name: Deploy to ArgoCD
        uses: ejhayes/action-argocd-deploy@releases/v1
        with:
          clientId: ${{ vars.ARGOCD_USERNAME }}
          clientSecret: ${{ secrets.ARGOCD_PASSWORD }}
          clusterName: ${{ vars.ARGOCD_CLUSTER_NAME }}
          baseUrl: ${{ vars.ARGOCD_SERVER }}
          name: cocktail-virt
          namespace: cocktail-virt
          project: default
          path: kubernetes
          valuesFile: kubernetes/values.yaml
          tokens: |
            TAG: ${{steps.package-version.outputs.current-version}}
            DOCKER_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{steps.package-version.outputs.current-version}}
          labels: |
            env: prod
          info: |
            rev: ${{ github.ref }}
            sha: ${{ github.sha }}
