name: Docker Image CI

on:
  push:
    branches:
      - "dev"
      - "main"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: namunorthamerica
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
  
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: namunorthamerica/hpc-virt:${{steps.package-version.outputs.current-version}}



      # Update kubernetes deployment with new image
      - name: Update kubernetes deployment
        run: |
          find ./kubernetes -type f -exec sed -i -E "s/__TAG__/${{steps.package-version.outputs.current-version}}/g" {} \;

      # Install ArgoCD CLI
      - name: Install argocd CLI
        run: |
          curl -sSL https://github.com/argoproj/argo-cd/releases/download/v2.7.7/argocd-linux-amd64 -o /usr/local/bin/argocd
          chmod +x /usr/local/bin/argocd

      # Login to ArgoCD before making API requests
      - name: Login to ArgoCD
        run: |
          argocd login ${{ vars.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app sync cocktail-virt

          